import "./globals.css";
import { inter } from "./components/font";

export const metadata = {
  title: "MEGG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased text-[#1F2421]`}
      >
        {children}
      </body>
    </html>
  );
}
